### PR TITLE
Add French locale

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by schomery** [comment]
Thanks!

**Comment by schomery** [comment]
Please also join https://www.transifex.com/github-7/popup-blocker-strict/dashboard/

**Comment by smed79** [comment]
I have submitted a request to add French (fr) and Arabic (ar) language.

**Comment by schomery** [comment]
Right! Seems that I had missed the email. Welcome to the team.

**Comment by smed79** [comment]
Thank you :-)

**Pull request merged**
